# Generated by Django 5.2.1 on 2026-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='percentual_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
