# Generated by Django 5.2.1 on 2026-04-01 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
